version: '3.2'

services:
  app:
    build: .
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 9000:8080
    stdin_open: true
    tty: true
    command: /bin/ash
